on:
  push:
    branches:
      - main
name: Linux_Container_Workflow

jobs:
    build-and-deploy:
        runs-on: ubuntu-latest
        steps:
        - name: 'Checkout GitHub Action'
          uses: actions/checkout@main

        - name: 'Build and push image'
          uses: azure/docker-login@v1
          with:
            login-server: ${{ secrets.REGISTRY_LOGIN_SERVER }}
            username: ${{ secrets.REGISTRY_USERNAME }}
            password: ${{ secrets.REGISTRY_PASSWORD }}
        - run: |
            docker build . -f Project.Api/Dockerfile -t ${{ secrets.REGISTRY_LOGIN_SERVER }}/project-x-api:latest -t ${{ secrets.REGISTRY_LOGIN_SERVER }}/project-x-api:${{ github.sha }}
            docker push ${{ secrets.REGISTRY_LOGIN_SERVER }}/project-x-api --all-tags
